### ISSUE TITLE
I need help with my save file

### ISSUE THREAD

**Issue by BoyBoy3124** [vswarte/eldenring_alt_saves#5]
Hey I installed the mod with modengine2 and it worked amazing but now I want to play multiplayer with that modded save, when I start my vanilla game it just prompts me to make a new game is there a fix for this I guess I missed something, thanks in advance

**Comment by vswarte** [comment]
hi are you still having this issue?

**Comment by BoyBoy3124** [comment]
Oh hey! I actually found what I did wrong I forgot to use the Elden save
copier so it works now, Tysm😊❤️

**Comment by vswarte** [comment]
Great to hear
