### ISSUE TITLE
Prevents Mod Engine 2 from launching when used with the latest version of the game

### ISSUE THREAD

**Issue by xuvvy** [vswarte/eldenring_alt_saves#6]
Launching Elden Ring through Mod Engine 2 with this DLL in the config file prevents the game from launching. I have not tested using Mod Loader instead of Mod Engine 2, but this started happening with the latest Elden Ring update (1.12) and the DLC (Shadow of the Erdtree) release.

**Comment by vswarte** [comment]
I assume you did update your version of the altsaves mod? Try this one if not: https://github.com/vswarte/eldenring_alt_saves/releases/tag/v1.3.2

**Comment by xuvvy** [comment]
> I assume you did update your version of the altsaves mod? Try this one if not: https://github.com/vswarte/eldenring_alt_saves/releases/tag/v1.3.2

My bad. It was the Nexus version of the mod, which hasn't been updated. I did not notice the latest update here.
